### PR TITLE
Change lang per user

### PR DESCRIPTION
**Pull request by Elikill58**
The objective of this PR is to add translation per user. Mostly https://github.com/Azuriom/Azuriom/pull/73 with more things and for Azuriom v1. (Real fix for https://github.com/Azuriom/Azuriom/issues/242).

Added:
- New button to change the lang (note: sadly, this have to be done for each theme)
image
- Changes admin part by adding way to select all lang that user can select:
image

Internal:
- Added new migration, to add column in user table about their option.
- Added new method in helpers that format locales codes.

As I know, Javdu10 is working on the "per plugin" part. Mostly the content by itself. If you want more changes, tell me. (Note: this is actually what I'm using for my own website and it's fine)

Note: Please use "SQUASH and merge" to prevent some ugly commits that I made.

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
Closing this as duplicate as the point of #73 and #242 are not addressed. From https://github.com/Azuriom/Azuriom/issues/242#issuecomment-1289121524

> This would be a great feature, but unfortunately this would be too complicated to implement in a proper way: all the built-in messages of Azuriom and it's plugins can be translated (and are also translated in many languages), **but all the website's content (settings, pages, posts, navbar, roles, shop items, wiki pages, FAQ questions, etc, etc) couldn't be translated in multiples different languages without massive changes. Because of this, the result of adding a language switcher would be half-translated website which wouldn't make much sense.**

However a feature like this could be released as a plugin if a website consider than an half-translated content make sense for them

**Comment by Elikill58** [comment]
I don't think it could be released as plugin as this is editing admin config part and already existing method.

Also, while I understand, it would be depending of what you are doing with the website. If you are using lite litebans, vote and a stats plugin, everything will be translated as all text generated by the plugin is translated, and in the case of those plugin, there is no user-input that should be translated.

When you're saying "this would be too complicated to implement in a proper way", for me I see you think it's too hard, but never start will not help. We can think about making some method/API to help plugins developers to add more translation. Also, AFTER this PR, we can implement all translations system in others plugins. This can NOT be done if we are using an external plugin.

If you really think this can be a great feature, let's talk about it and see how we can do. Keep closing such PR is -for me- keep blocking the advancement of this feature.

**Comment by Javdu10** [comment]
Translating the content of other plugins from within a plugin is possible, it is just a one way operation, meaning if you set the multi language you cannot go back

One day I'll release the plugin but it is not complete yet and I am working on other things

**Comment by MrMicky-FR** [comment]
> I don't think it could be released as plugin as this is editing admin config part and already existing method.

It could definitely be released as a plugin, just that the config in the admin dashboard would be the plugin config instead of in the global settings, but it would make no difference for the users.

>  If you are using lite litebans, vote and a stats plugin, everything will be translated as all text generated by the plugin is translated, and in the case of those plugin, there is no user-input that should be translated.

Even without any plugin, all the theme settings, the navbar, the posts, pages, copyright and tons of other texts wouldn’t be translated. With votes, the same goes for the rewards names.

> When you're saying "this would be too complicated to implement in a proper way", for me I see you think it's too hard, but never start will not help.

A proper roadmap could definitely be in the continuity of the discussion, but just implementing an half-finished function is not a good start IMHO

**Comment by Elikill58** [comment]
Theme are already translated. For others, yes that's write.

> A proper roadmap could definitely be in the continuity of the discussion
I think it's a good start. Try to determine how to do, determine what should be done step by step and then do it for everyone to have a perfect translation system.

Until this, I'll keep my home-made thing x)

**Pull request closed without merging**
