### PR TITLE
Change API provider for MC head

### PR DESCRIPTION
**Pull request by SiriHackYT**
Change API provider for MC head because the last one is now inactive

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
CraftHead is working fine for me: 



Have you any example of link which isn’t working properly ?

**Comment by SiriHackYT** [comment]
For me and other players, CraftHead print my skin of October 2021, so this api is not updated

**Comment by ArnaudLier** [comment]
Related: https://github.com/astei/crafthead/issues/63

**Comment by modcrafts** [comment]
CraftHead is not accessible in mainland China

**Comment by modcrafts** [comment]
McHeads is not accessible in mainland China 😢

**Comment by MrMicky-FR** [comment]
> McHeads is not accessible in mainland China 😢

Not sure which provider we can use, as we already moved from Minotar and CraftHead due to issues. But if you need you can change the provider here:
https://github.com/Azuriom/Azuriom/blob/8f4a6ad95e67f4aba42ef693b3a2eb263edf35b1/app/Games/Minecraft/MinecraftOfflineGame.php#L27

**Pull request merged**
