### PR TITLE
Add Sitemap Generation

### PR DESCRIPTION
**Pull request by scarecr0w12**
-Add sitemap.xml to gitignore
-update composer to include 'spatie/laravel-sitemap'
-Add Daily App run to regenerate sitemap
-Added artisan command for 'app:generate-sitemap'

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
Can you add an example of a generated sitemap ?

**Comment by scarecr0w12** [comment]
Yup, have it currently generating on my site right now:
https://www.thecgn.net/sitemap.xml

Passes googles search console too
image

**Comment by scarecr0w12** [comment]
I would note, i did not set it up with a fully fleshed out profiling system to include images, videos and the like, it simply does URLs at the moment, but im more than willing to expand on it.

**Comment by MrMicky-FR** [comment]
Hum I’m not sure to see the point of the generated sitemap: it’s made by crawling the website, exactly like a search engine will do.
Even [Google](https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview) says that sitemaps aren’t necessary for websites with >500 pages or correct cross-links.

The other features of sitemaps are `priority`, `changefreq` and `lastmod`, which none of them is included

**Comment by MrMicky-FR** [comment]
Closing for inactivity, and seems like to be no benefits and the tests are failing

**Pull request closed without merging**
