### PR TITLE
feat/Add_diff_in_action_logs#147

### PR DESCRIPTION
**Pull request by vassilidev**
Feature(Add diff in action logs): Add the possibility to register automatically changed value into the database.

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
Thanks, just two things:
* I think a dedicated page for each log would be better than a modal, to make easier to read changes with long values (like posts, pages, etc) and prevent loading all the changes in the logs index page
* The current implementation could lead to a stored XSS if a user can control the attributes of any logged model (including the user itself), because the raw JSON isn't escaped, which is pretty dangerous.

**Comment by vassilidev** [comment]
Yes, it was a proposal, no ones ask or tell what u want so..

**Comment by vassilidev** [comment]
and u dont have XSS with @json : test @json("<script>alert('toto')</script>")

**Comment by MrMicky-FR** [comment]
> Yes, it was a proposal, no ones ask or tell what u want so.. with or without modal, its kinda the same

Yes that's why I make this suggestion :)

> Even if with only the `@json` tag there is no XSS, the issue is that the JSON content is decoded and inserted as raw HTML with JS on modal open

**Comment by vassilidev** [comment]
Okay, I'll do a separate page for the data.

Or maybe some one can do it easly, just remove the modal + "component" and that's it

**Comment by MrMicky-FR** [comment]
Thanks, added in https://github.com/Azuriom/Azuriom/commit/95002fe13324497dbd3e955be65f7da8df9b27ea 👍

**Pull request closed without merging**
